apiVersion: v1
kind: Service
metadata:
    name: "coolapi-service"
    namespace: coolapi
    labels:
        app: "coolapi"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "coolapi"
